### ISSUE TITLE
cannot find yaml to set up a friendly name for temp/hum sensor

### ISSUE THREAD

**Issue by sergiotomasello** [lazcad/homeassistant#43]
which is the yaml to customize temperature/humidity sensor?
In the docs I only found the yaml for `binary sensor`

```yaml
  customize:
    binary_sensor.switch_158d000xxxxxc3:
        friendly_name: Ktichen Switch
    binary_sensor.switch_158d000xxxxxc2:
        friendly_name: Table Switch
    binary_sensor.door_window_sensor_158d000xxxxx7a:
        friendly_name: Door Sensor
```

Regards
Sergio
