### ISSUE TITLE
Wrong time duration with motion sensors

### ISSUE THREAD

**Issue by replayfactory** [lazcad/homeassistant#48]
When using motion sensor in trigger, time duration is incorrect.

```
trigger:
  platform: state
  entity_id: binary_sensor.motion_sensor_158d000113d149
  to: 'off'
  for:
    seconds: 60            # Trigger fire at 3 minutes
    # seconds: 120         # Trigger fire at 6 minutes

```
Same code with a binary_sensor.switch or switch.plug work perfectly

```
Home Assistant  : 0.42.4
Xiaomi firmware : 1.4.1_145.0141
```
