### ISSUE TITLE
Does Not Work

### ISSUE THREAD

**Issue by wajidp** [lazcad/homeassistant#50]
automation:
- alias: TriggerTBOT
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000129161b
    from: 'no_motion'
    to: 'motion'
  action:
     service: notify.TBOT
     data:
      message: Door opened

I can see the motion sensor is turned in home assistant page but the action is not triggered

**Comment by tringler** [comment]
Try it like this.:
```
  trigger:
    platform: event
    event_type: motion
    event_data:
        entity_id: binary_sensor.motion_sensor_158d000113702f
```
