### ISSUE TITLE
Multiple Events for Single Click Button

### ISSUE THREAD

**Issue by choongyouqi** [lazcad/homeassistant#55]
My automation script always got triggered 3 times every time I press the xiaomi zigbee button once. any idea? (I verify by putting a pushbullet notifier in the action)

Below is my automation code:
```yaml
- alias: Turn on SPHERE when button click once
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001138943
      click_type: single
  action:
    - service: notify.pushbullet
      data_template: {"message": "button single", "target": ["email/myemail@gmail.com"]}
    - service: homeassistant.turn_on
      entity_id: light.hue2__sphere
      data:
        xy_color: [0.4596, 0.4105]
        brightness: 254
        transition: 1
```
